# Generated by Django 2.2.10 on 2020-05-18 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchaGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchaGameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective', models.DateTimeField(auto_now_add=True)),
                ('state', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matcha.MatchaGame')),
            ],
            options={
                'unique_together': {('game', 'effective')},
            },
        ),
    ]
