version: '3'

networks:
  default:
    external:
      name: web

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  ackwire:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: ack_wire_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ack_wire_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6

