# Generated by Django 2.2.10 on 2020-04-07 15:16

from django.db import migrations


def migrate_data(apps, schema_editor):
    import json

    GameState = apps.get_model('game', 'GameState')
    for gs in GameState.objects.all():
        state = json.loads(gs.state)
        state['schedule'] = [200, 200, 200, 300, 400, 500, 600, 600, 600, 600, 600, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 900, 900, 900, 900, 900, 900, 900, 900, 900, 900, 1000]
        state['chain_costs'] = {
            "Luxor": 0,
            "Tower": 0,
            "American": 100,
            "Festival": 100,
            "Worldwide": 100,
            "Continental": 200,
            "Imperial": 200,
        }
        gs.state = json.dumps(state)
        gs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190305_0320'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop)
    ]
