# Generated by Django 2.2.10 on 2020-04-13 21:44

from django.db import migrations


def migrate_data(apps, schema_editor):
    import json

    GameState = apps.get_model('game', 'GameState')
    for gs in GameState.objects.all():
        state = json.loads(gs.state)
        if 'variants' not in state:
            state['variants'] = []
            gs.state = json.dumps(state)
            gs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_double_tiles_variant'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop)
    ]
