# Generated by Django 2.2.10 on 2020-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200413_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='no_2player_tile_draw_variant',
            field=models.BooleanField(default=False),
        ),
    ]
